### ISSUE TITLE
SetItem option behaviour 

### ISSUE THREAD

**Issue by ErnestBrandi** [KaneCohen/tokenfield#41] opened 2019-02-21 17:04 UTC
Hi,
I noticed a couple of things, I'm not sure if it's desired or not.
First when you fill up your tokenfield on creation with setItem option; if there is only one token the Placeholder is displayed, but disappear with two or more (it does not seem to depend on the size of the placeholder or the size of the field).
Secondly, and this is more an issue, data added that way does not prevent to enter the same token again when gathered with via remote data. 
Cheers

**Comment by KaneCohen** [comment] 2019-02-21 17:34
@ErnestBrandi Issue with placeholder should be fixed in 1.2.1.
However I can't reproduce the second issue.

Could you share the code sample where you create the tokenfield instance and also a sample of remote data.

**Comment by ErnestBrandi** [comment] 2019-02-21 18:16
I found the reason why. That's because you are comparing setItems and remote data ids (and not text content itself). This is not ideal, for example in my case I have on one side user specific tokens that I enter through the setItems option, and on the other tokens entered by every users that are gathered through the remote url process. The ids are therefore not correlated !

**Comment by KaneCohen** [comment] 2019-02-21 19:10
You could try setting following option:

```js
   itemValue: 'name'
```

**Comment by ErnestBrandi** [comment] 2019-02-22 08:35
That solution suits me very well.

**Closed** 2019-02-22 08:36 UTC
